# Q.1) Replace Nan with 0 and Interchange 3 rows and 3 columns of 2D array [[6, -8, 73, -110], [np.nan, -8, 0, 94]]

In [15]:
import pandas as pd
import numpy as np

l = np.array([
    [6, -8, 73, -110],
    [np.nan, -8, 0, 94]
])

print("\n-----2D Array-----\n")

print(l)

#replacing NaN using array indexing

l[1][0] = 0

print("\n-----Replaced NaN with 0-----\n")
print(l)

#Interchange Rows

l[[1,0]] = l[[0,1]]

print("\n-----Interchanged Rows-----\n")

print(l)

#InterChange 3 Columns

l[:, [0,1,2]] = l[:, [2,0,1]]

print("\n-----Interchanged 3 Columns-----\n")

print(l)


-----2D Array-----

[[   6.   -8.   73. -110.]
 [  nan   -8.    0.   94.]]

-----Replaced NaN with 0-----

[[   6.   -8.   73. -110.]
 [   0.   -8.    0.   94.]]

-----Interchanged Rows-----

[[   0.   -8.    0.   94.]
 [   6.   -8.   73. -110.]]

-----Interchanged 3 Columns-----

[[   0.    0.   -8.   94.]
 [  73.    6.   -8. -110.]]


# Q.2) Move axes of 3D array to new positions 

In [23]:
#Create 3D Array

l = np.array([
    [[1,2],
     [3,4],
     [5,6]],
    
    [[7,8],
     [9,10],
     [11,12]]
])

print("\n-----3D Array-----\n")
print(l)
print("\nShape :",l.shape)

#Move axes by using moveaxis()

new_l = np.moveaxis(l, [0,1,2], [2,0,1])

print("\n-----After Moving Axes-----\n")
print(new_l)

print("\nNew Shape :",new_l.shape)


-----3D Array-----

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]

Shape : (2, 3, 2)

-----After Moving Axes-----

[[[ 1  7]
  [ 2  8]]

 [[ 3  9]
  [ 4 10]]

 [[ 5 11]
  [ 6 12]]]

New Shape : (3, 2, 2)


# Q.3) Replace NaN values with average of columns

In [29]:
#Make list

l = np.array([
    [1,2,3,np.nan],
    [3,2,np.nan,5],
    [7,np.nan,10,8]
])

print("\n-----Array-----\n")
print(l)

#column mean using nanmean()

col_mean = np.nanmean(l,axis = 0)
print("\n-----Column Mean Ignoring NaN values-----\n")
print(col_mean)

#Find the Positions of the NaN Values
positions = np.where(np.isnan(l))
print("\n-----Positions of the NaN Values-----\n")
print(positions)

#Replace the NaN values With mean
l[positions] = np.take(col_mean, positions[1])

print("\n-----Replacing NaN with Corresponding col_mean-----\n")
print(l)


-----Array-----

[[ 1.  2.  3. nan]
 [ 3.  2. nan  5.]
 [ 7. nan 10.  8.]]

-----Column Mean Ignoring NaN values-----

[3.66666667 2.         6.5        6.5       ]

-----Positions of the NaN Values-----

(array([0, 1, 2]), array([3, 2, 1]))

-----Replacing NaN with Corresponding col_mean-----

[[ 1.   2.   3.   6.5]
 [ 3.   2.   6.5  5. ]
 [ 7.   2.  10.   8. ]]


# Q.4) Replace negative value with zero in numpy array using replace

In [35]:
#Make array with negative values

print("\n-----Use Conditional Statement-----\n")
l = np.array([
    [1,-5,-3,2],
    [-7,6,7,-9]
])

#numpy array doesnt have replace function pandas do have
print("\n-----Before Replacement-----\n")
print(l)

#We Use Conditional Statement

l[l < 0] = 0
print("\n-----After Replacement-----\n")
print(l)

print("\n-----#Alternatively, we can use np.where()#-----\n")

l = np.array([
    [1,-5,-3,2],
    [-7,6,7,-9]
])

print("\n-----Before Replacement-----\n")
print(l)

new_arr = np.where(l < 0, 0,l)
print("\n-----After Replacement-----\n")
print(new_arr)


-----Before Replacement-----

[[ 1 -5 -3  2]
 [-7  6  7 -9]]

-----After Replacement-----

[[1 0 0 2]
 [0 6 7 0]]

-----#Alternatively, we can use np.where()#-----


-----Before Replacement-----

[[ 1 -5 -3  2]
 [-7  6  7 -9]]

-----After Replacement-----

[[1 0 0 2]
 [0 6 7 0]]
