# Q.1) Create numpy array and perform following operation : 
# Convert 1D array to 2D.
# Print Array Attributes(Like shape, dimenssion, data type, itemsize). 
# Create a 3×3 NumPy array of all 9.
# Create a 1D array of 10 evenly spaced values between 25 and 125.
# Convert a Python list into a NumPy array > Reverse a 1D NumPy array.
# Create a 4×4×3 array and extract value at its second set, first row and last column.
# Create a 4×4 and Extract Odd Rows and Even Columns.
# Slice the first two rows and first two columns of econd set from a 4×4×3 array. 
# Replace all odd numbers in a NumPy array with -1 by itterating using for loop [[23, 56, 78, 93], [71, 82,13, 24]]. 
# Get the indices of non-zero elements in an array [1, 0, 2, 0, 3, 0, 4].
# Perform arithmetic operations on two NumPy arrays element-wise Add two NumPy arrays element by element. Multiply two NumPy arrays element by element. 
# Write a code to compute the dot product of two NumPy arrays arr1 = [15, 20, 25] arr2 = [10,40,37].

In [55]:
#Convert 1D to 2D

import numpy as np

print("\n-----Convert 1D to 2D-----")
arr = np.array([1,2,3,4,5,6])

print("\n---1D Array---\n",arr)

new_arr = arr.reshape(2,3)

print("\n---2D Array---\n",new_arr)

#Array Attributes

print("\n-----Array Attributes-----")

print("\nShape :",new_arr.shape)
print("\nDimension :",new_arr.ndim)
print("\nData Type :",new_arr.dtype)
print("\nItem Size :",new_arr.itemsize)

# 3×3 array of all 9s
arr = np.full((3, 3), 9)
print("\n---3x3 Array---\n", arr)

# 10 evenly spaced values between 25 and 125
arr = np.linspace(25, 125, 10)
print("\n---Array is---\n", arr)


#Convert List to NP Array and Reverse it

print("\n-----Convert List to NP Array and Reverse it-----")

l = ([1,2,3,4,5,6])
print("\n---List---\n", l)
new_l =  np.array(l)
print("\n---NumPy Array---\n", new_l)

#Reverse
print(f"\n---Reverse of {new_l}---\n", new_l[::-1] )

#Create 4x4x3 array
print("\n-----Create 4x4x3 array and Extract the value-----")

arr = np.arange(48).reshape(4,4,3)

print("\n---Array is---\n", arr)

print("\nValue At second set, first row and last column :", arr[1,0,-1])

#Create a 4x4 and extract odd rows and even columns

print("\n-----Create a 4x4 and extract odd rows and even columns-----")

arr = np.arange(16).reshape(4, 4)

print("\n---Array---\n")
print(arr)

print("\n---Odd Rows (1st and 3rd)---\n")
print(arr[::2])

print("\n---Even Columns (2nd and 4th)---\n")
print(arr[:, 1::2])

#Slice the first two rows and first two columns of second set from a 4×4×3 array.

print("\n-----Slice the first two rows and first two columns of second set from a 4×4×3 array-----")

arr = np.arange(48).reshape(4,4,3)

print("\n---Array is---\n", arr)

result = arr[1, :2, :2]

print("\n---Result is---\n", result)


-----Convert 1D to 2D-----

---1D Array---
 [1 2 3 4 5 6]

---2D Array---
 [[1 2 3]
 [4 5 6]]

-----Array Attributes-----

Shape : (2, 3)

Dimension : 2

Data Type : int64

Item Size : 8

---3x3 Array---
 [[9 9 9]
 [9 9 9]
 [9 9 9]]

---Array is---
 [ 25.          36.11111111  47.22222222  58.33333333  69.44444444
  80.55555556  91.66666667 102.77777778 113.88888889 125.        ]

-----Convert List to NP Array and Reverse it-----

---List---
 [1, 2, 3, 4, 5, 6]

---NumPy Array---
 [1 2 3 4 5 6]

---Reverse of [1 2 3 4 5 6]---
 [6 5 4 3 2 1]

-----Create 4x4x3 array and Extract the value-----

---Array is---
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]

 [[36 37 38]
  [39 40 41]
  [42 43 44]
  [45 46 47]]]

Value At second set, first row and last column : 14

-----Create a 4x4 and extract odd rows and even columns-----

---Array---

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 

In [56]:
# Replace all odd numbers in a NumPy array with -1 by itterating using for loop [[23, 56, 78, 93], [71, 82,13, 24]]

print("\n-----Replace of Odd numbers-----")
l =  np.array([
    [23, 56, 78, 93], 
    [71, 82,13, 24]
])

print("\n---Array---\n", l)

for x in range(l.shape[0]):
    for y in range(l.shape[1]):
        if l[x][y] % 2 != 0:
            l[x][y] = -1

print("\n---After Replacing---\n", l)

#Indices Of Non Zero elements

print("\n-----Get the indices of non-zero elements in an array [1, 0, 2, 0, 3, 0, 4]-----")

l = np.array([1, 0, 2, 0, 3, 0, 4])

print("\n---Array is---\n", l)

indices_l = []

for x in range(l.size):
    if l[x] > 0:
        indices_l.append(x)

print("\n---Indices List---\n",np.array(indices_l))



-----Replace of Odd numbers-----

---Array---
 [[23 56 78 93]
 [71 82 13 24]]

---After Replacing---
 [[-1 56 78 -1]
 [-1 82 -1 24]]

-----Get the indices of non-zero elements in an array [1, 0, 2, 0, 3, 0, 4]-----

---Array is---
 [1 0 2 0 3 0 4]

---Indices List---
 [0 2 4 6]


In [67]:
# Perform arithmetic operations on two NumPy arrays element-wise Add two NumPy arrays element by element. Multiply two NumPy arrays element by element

print("""\n-----Perform arithmetic operations on two NumPy arrays element-wise 
Add two NumPy arrays element by element. Multiply two NumPy arrays element by element-----""")

arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

print("\n---Array 1---\n", arr1)
print("\n---Array 2---\n", arr2)

# Addition
add = arr1 + arr2

# Multiplication
mul = arr1 * arr2

print("\n---Element-wise Addition---\n", add)
print("\n---Element-wise Multiplication---\n", mul)

#Code to compute the dot product of two NumPy arrays arr1 = [15, 20, 25], arr2 = [10,40,37].

print("\n-----Code to compute the dot product of two NumPy arrays arr1 = [15, 20, 25] arr2 = [10,40,37]-----")

arr1 = np.array([15, 20, 25])
arr2 = np.array([10, 40, 37])

print("\n---Array 1---\n", arr1)
print("\n---Array 2---\n", arr2)

res = arr1.dot(arr2)

print(f"\nDot Product of {arr1} and {arr2} :",res)



-----Perform arithmetic operations on two NumPy arrays element-wise 
Add two NumPy arrays element by element. Multiply two NumPy arrays element by element-----

---Array 1---
 [10 20 30 40]

---Array 2---
 [1 2 3 4]

---Element-wise Addition---
 [11 22 33 44]

---Element-wise Multiplication---
 [ 10  40  90 160]

-----Code to compute the dot product of two NumPy arrays arr1 = [15, 20, 25] arr2 = [10,40,37]-----

---Array 1---
 [15 20 25]

---Array 2---
 [10 40 37]

Dot Product of [15 20 25] and [10 40 37] : 1875
