# Q.1) Combining a one and a two-dimensional NumPy Array

In [8]:
#Create 1D and 2D NumPy Array

import numpy as np

l1 = np.array([1,2,3,4])

l2 = np.array([
    [6,7,8,9],
    [10,11,12,13]
])

print("\n---1D Array---\n", l1)
print("\n---2D Array---\n", l2)

#Combining 1D and 2D Array

new_l = np.concatenate((l2,[l1]), axis = 0)
print("\n---Combination Of 1D and 2D Array---\n",new_l)


---1D Array---
 [1 2 3 4]

---2D Array---
 [[ 6  7  8  9]
 [10 11 12 13]]

---Combination Of 1D and 2D Array---
 [[ 6  7  8  9]
 [10 11 12 13]
 [ 1  2  3  4]]


# Q.2) Flatten a 2d numpy array into 1d array

In [13]:
#Create a 2D Array

l = np.array([
    [1,2,3],
    [4,5,6]
])

print("\n---2D Array---\n", l)

#Use reshape(-1)

new_l = l.reshape(-1)
print("\n---Flatten Array---\n", new_l)


---2D Array---
 [[1 2 3]
 [4 5 6]]

---Flatten Array---
 [1 2 3 4 5 6]


# Q.3) Reverse a numpy array

In [19]:
l = np.array([1,2,3,4,5,6])

print("\n---Array---\n", l)
new_l = l[::-1]

print("\n---Reversed Array---\n", new_l)
    


---Array---
 [1 2 3 4 5 6]

---Reversed Array---
 [6 5 4 3 2 1]


# Q.4) Practice operations:
# Get the maximum value from given array 
# Get the minimum value from given array 
# Find the number of rows and columns of a given array using NumPy 
# Select the elements from a given array (each element and specific element) 
# Find the sum of values in a 2D array using for loop 
# Adding, Subtracting, multiplying, dividing arrays in Numpy 

In [47]:
#Max Value
print("\n------Minimum and Maximum in NumPy Array------\n")
arr = np.array([23, 21, 45, 67, 10, 28, 34, 32])

print(f"\nMaximum Value in {arr} is: {arr.max()}")

#Min Value

print(f"Minimum Value in {arr} is: {arr.min()}")

#Number Of Rows and Columns
print("\n------Number Of Rows and Columns in NumPy Array------\n")

arr = np.array([
    [34,2,3,45,6],
    [2,3,45,6,75],
    [32,100,32,55,89]
])

print("\n---Array---\n", arr)

val = arr.shape

print("\nNumber Of Rows: ",val[0])
print("Number Of Columns: ",val[1])

#Select the Elements
print("\n------Select Individual And Specific Elements------\n")

arr = np.array([
    [34,2,3,45,6],
    [2,3,45,6,75],
    [32,100,32,55,89]
])

print("\nElement From 2nd row and 3rd Column :", arr[1][2])
print("Element From 3rd row and 4th Column :", arr[2][3])
print("Element From 1st row and 5th Column :", arr[0][4])

#Sum Of Elements In a 2D Array
print("\n------Sum of Elements in 2D Array------\n")

arr = np.array([
    [34,2,3,45,6],
    [2,3,45,6,75],
    [32,100,32,55,89]
])

print("\n---Array---\n", arr)

sum = 0

for x in arr:
    for y in x:
        sum += y

print("\nSum = ",sum)

#Adding, Subtracting, Multiplying, Dividing arrays in Numpy
print("\n------Adding, Subtracting, Multiplying, Dividing arrays in Numpy------\n")
l1 = np.array([10,20,30,40,50])
l2 = np.array([1,2,3,4,5])

print("\n---Array 1---\n", l1)
print("\n---Array 2---\n", l2)

print("\n---Addition---\n", l1 + l2)
print("\n---Subtraction---\n", l1 - l2)
print("\n---Multiplication---\n", l1 * l2)
print("\n---Division---\n", l1 / l2)


------Minimum and Maximum in NumPy Array------


Maximum Value in [23 21 45 67 10 28 34 32] is: 67
Minimum Value in [23 21 45 67 10 28 34 32] is: 10

------Number Of Rows and Columns in NumPy Array------


---Array---
 [[ 34   2   3  45   6]
 [  2   3  45   6  75]
 [ 32 100  32  55  89]]

Number Of Rows:  3
Number Of Columns:  5

------Select Individual And Specific Elements------


Element From 2nd row and 3rd Column : 45
Element From 3rd row and 4th Column : 55
Element From 1st row and 5th Column : 6

------Sum of Elements in 2D Array------


---Array---
 [[ 34   2   3  45   6]
 [  2   3  45   6  75]
 [ 32 100  32  55  89]]

Sum =  529

------Adding, Subtracting, Multiplying, Dividing arrays in Numpy------


---Array 1---
 [10 20 30 40 50]

---Array 2---
 [1 2 3 4 5]

---Addition---
 [11 22 33 44 55]

---Subtraction---
 [ 9 18 27 36 45]

---Multiplication---
 [ 10  40  90 160 250]

---Division---
 [10. 10. 10. 10. 10.]


# Q.5) Iterate 3D array using for loop and nditer

In [53]:
#Using For Loop

arr = np.array([
    [[1,2,3,4],
     [5,6,7,8]],
    [[9,10,11,12],
     [13,14,15,16]]
])

print("\n-----3D Array-----\n", arr)

print("\n---Using For Loop----\n")
for x in arr:
    for y in x:
        for z in y:
            print(z, end = " ")

print()
#Using np.nditer
print("\n----Using np.nditer()----\n")
for x in np.nditer(arr):
    print(x, end = " ")


-----3D Array-----
 [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]

---Using For Loop----

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 

----Using np.nditer()----

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 

# Q.6) Study the following program 
# Import numpy as np 
# create a numpy 1d-arrays arr1 = np.array([3, 4]) arr2 = np.array([1, 0]) 
# find average of NumPy arrays avg = (arr1 + arr2) / 2, print("Average of NumPy arrays:\n", avg)
# Calculate average mean median mode values of two NumPy 2d-arrays

In [90]:
import numpy as np

print("\n---Average of 2 1D NumPy Arrays---\n")
arr1 = np.array([3,4])
arr2 = np.array([1,0])

print("\n---Array 1---\n", arr1)
print("\n---Array 2---\n", arr2)

#Average

avg = (arr1 + arr2) / 2

print("\nAverage Of arr1 and arr2 : ", avg)

#Mean,Median and Mode
print("\n---Mean, Median, Mode of 2 2D NumPy Arrays---")

arr1 = np.array([
    [1,1],
    [3,4]
])
arr2 = np.array([
    [5,6],
    [2,8]
])

print("\n---Array 1---\n", arr1)
print("\n---Array 2---\n", arr2)

print("\nMean of Combined arr1 and arr2 : \n", np.mean([arr1,arr2]))
print("\nMedian of Combined arr1 and arr2 : \n", np.median([arr1,arr2]))

print("\n---Flatten Array---")
flat_arr = np.concatenate([arr1.reshape(-1),arr2.reshape(-1)])
print(flat_arr)

l = np.zeros(flat_arr.max() + 1, dtype = int)
print("\n---Frequency Array---\n", l)

for x in flat_arr:
    l[x] += 1 

print("\n---After Frequency Count---")
print(l)

for x in range(l.size - 1):
    if l[x] == l.max():
        mode = x
print("\nMode of the Combined arr1 and arr2 :\n", mode)


---Average of 2 1D NumPy Arrays---


---Array 1---
 [3 4]

---Array 2---
 [1 0]

Average Of arr1 and arr2 :  [2. 2.]

---Mean, Median, Mode of 2 2D NumPy Arrays---

---Array 1---
 [[1 1]
 [3 4]]

---Array 2---
 [[5 6]
 [2 8]]

Mean of Combined arr1 and arr2 : 
 3.75

Median of Combined arr1 and arr2 : 
 3.5

---Flatten Array---
[1 1 3 4 5 6 2 8]

---Frequency Array---
 [0 0 0 0 0 0 0 0 0]

---After Frequency Count---
[0 2 1 1 1 1 1 0 1]

Mode of the Combined arr1 and arr2 :
 1
